nginx:
    build: ./nginx
    links:
        - node1:node1
    ports:
        - "49160:80"
node1:
    build: ./
    links:
        - redis
    ports:
        - "4000"
    volumes:
        - ./:/var/www/app
    command: npm run dev
redis:
    image: redis:4-alpine
    ports:
        - "6379"
