version: '3'
services:
  nginx:
    build:
      context: ./nginx
    links:
        - node1:node1
    ports:
        - "49160:80"
  node1:
    build:
      context: ./
    links:
        - redis
        - mongodb
    ports:
        - "4000"
    volumes:
        - ./:/var/www/app
    command: npm run dev
  redis:
    image: redis:4-alpine
    ports:
        - "6379"
  mongodb:
    image: mongo:3.6
    volumes:
        - ./data:/data/db
    ports:
        - "27017:27017"
